version: '2'
services:
  web:
    build: .
    ports:
     - "5000:5000"
    volumes:
     - .:/app
    links:
     - db
    container_name: ps_web_api
    depends_on:
     - db
  db:
    image: mongo:latest
    container_name: "ps_mongodb"
    restart: always
    privileged: true
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - /var/mongo_data:/data/db
    ports:
      - 27017:27017
    command: mongod --smallfiles --logpath=/dev/null # --quiet