version: '2'
services:
  web:
    build: .
    ports:
     - "5000:5000"
    volumes:
     - .:/app
    links:
     - influxdb
    environment:
      - INFLUX_HOST=influxdb
      - INFLUX_USER=web
      - INFLUX_USER_PASSWORD=pwd
    container_name: ps_web_api
    depends_on:
     - influxdb

  influxdb:
    image: "influxdb:alpine"
    container_name: ps_influxdb
    restart: always
    # DO NOT use in production
    # use secret field instead
    environment:
     - INFLUXDB_GRAPHITE_ENABLED=true
     - INFLUXDB_DB=energy_service
     - INFLUXDB_ADMIN_ENABLED=true
     - INFLUXDB_ADMIN_USER=admin
     - INFLUXDB_ADMIN_PASSWORD=pwd
     - INFLUXDB_USER=web
     - INFLUXDB_USER_PASSWORD=pwd
    ports:
     - "8083:8083"
     - "8086:8086"
     - "2003:2003"
    volumes:
     - ./data:/var/lib/influxdb